# Generated by Django 5.0.1 on 2024-02-17 10:30

import backend.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='FinanceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hq_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TechSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30, validators=[backend.validators.NameValidator()])),
                ('last_name', models.CharField(max_length=30, validators=[backend.validators.NameValidator()])),
                ('company', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('contact_number', models.CharField(max_length=20, validators=[backend.validators.ContactNumberValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('interests', models.ManyToManyField(related_name='users', to='api.interest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('vertex_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity')),
                ('finance_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financestage')),
                ('hq_main_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainoffice')),
                ('tech_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techsector')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
