# Generated by Django 5.0.1 on 2024-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tech_sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vertex_entity',
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='company',
            name='tech_sector',
            field=models.ManyToManyField(related_name='companies_tech_sector', to='api.techsector'),
        ),
        migrations.AddField(
            model_name='company',
            name='vertex_entity',
            field=models.ManyToManyField(related_name='companies_hq_main_office', to='api.entity'),
        ),
    ]
