# Generated by Django 5.0.1 on 2024-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_contact_number_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('tech_sector', models.CharField(max_length=100)),
                ('main_office', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
