# Generated by Django 5.0.1 on 2024-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_tech_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tech_sector',
            field=models.ManyToManyField(blank=True, related_name='companies_tech_sector', to='api.techsector'),
        ),
    ]
