# Generated by Django 5.0.1 on 2024-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_tech_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customers_partners',
            field=models.TextField(blank=True, null=True, verbose_name='Current customers and partners'),
        ),
        migrations.AddField(
            model_name='company',
            name='founders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pricings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
