# Generated by Django 5.0.1 on 2024-02-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_company_status_delete_option_company_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='entity_type',
            new_name='finance_stage',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='main_office',
            new_name='hq_main_office',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='stage',
            new_name='vertex_entity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag',
        ),
    ]
