# Generated by Django 5.0.1 on 2024-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_company_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='vertex_entity',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='hq_main_office',
            new_name='main_office',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='finance_stage',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
