# Generated by Django 5.0.2 on 2024-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_interest_remove_user_interests_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='api.interest'),
        ),
    ]
