# Generated by Django 5.0.1 on 2024-02-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_vertex_entity_company_entity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='main_office',
        ),
    ]
