# Generated by Django 5.0.1 on 2024-02-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_office',
            field=models.CharField(default='defualt', max_length=100),
            preserve_default=False,
        ),
    ]
