# Generated by Django 5.0.1 on 2024-02-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_company_main_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='stage',
            new_name='finance_stage',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='main_office',
            new_name='hq_main_office',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='entity_type',
            new_name='vertex_entity',
        ),
    ]
