# Generated by Django 5.0.1 on 2024-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_company_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tech_sector',
            field=models.CharField(max_length=10000),
        ),
    ]
