# Generated by Django 5.0.1 on 2024-02-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_interests'),
        ('api', '0017_alter_company_tech_sector'),
    ]

    operations = [
    ]
