# Generated by Django 5.0.1 on 2024-02-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240215_1519'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='api_company',
        ),
    ]
