# Generated by Django 5.0.1 on 2024-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_company_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
