# Generated by Django 5.0.1 on 2024-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=100000)),
                ('tech_sector', models.CharField(max_length=10000)),
                ('hq_main_office', models.CharField(max_length=100)),
                ('vertex_entity', models.CharField(max_length=100)),
                ('finance_stage', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
