# Generated by Django 5.0.1 on 2024-02-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='FinanceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hq_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TechSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='vertex_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entity'),
        ),
        migrations.AlterField(
            model_name='company',
            name='finance_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financestage'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_main_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainoffice'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tech_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techsector'),
        ),
    ]
