name: Frontend Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "Sprint-2"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Components
        run: |
          cd frontend
          npm install

      - name: Run Frontend test
        run: |
          cd frontend
          npm test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
